# Generated by Django 6.0.6 on 2026-06-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_code', models.CharField(max_length=50, unique=True)),
                ('max_temperature_celsius', models.IntegerField()),
                ('last_calibrated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('assinged_engineers', models.ManyToManyField(related_name='assigned_parts', to='parts.engineer')),
                ('specification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='parts.technicalspecification')),
            ],
        ),
    ]
