# Generated by Django 6.0.6 on 2026-06-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='assinged_engineers',
            new_name='assigned_engineers',
        ),
    ]
